#!/bin/sh

output_config() {
	echo "multigraph autobahn_a7"
	echo "graph_title A7 Verkehrswarnungen"
	echo "graph_info Verkehrswarnungen der Autobahn GmbH"
	echo "graph_vlabel Warnungen"
	echo "graph_args --base 1000"
	echo "graph_category autobahn"
	output_labels "A7"
	echo "multigraph autobahn_a8"
	echo "graph_title A8 Verkehrswarnungen"
	echo "graph_info Verkehrswarnungen der Autobahn GmbH"
	echo "graph_vlabel Warnungen"
	echo "graph_args --base 1000"
	echo "graph_category autobahn"
	output_labels "A8"
}

output_labels() {
	python3 -c "
routes = []
autobahn = \"$1\"
if autobahn == \"A8\":
	routes = [\"Salzburg Richtung München\", \"München Richtung Salzburg\", \"München Richtung Stuttgart\", \"Stuttgart Richtung München\", \"Stuttgart Richtung Karlsruhe\", \"Karlsruhe Richtung Stuttgart\"]
elif autobahn == \"A7\":
		routes = [\"Füssen/Reutte Richtung Ulm\", \"Ulm Richtung Füssen/Reutte\", \"Ulm Richtung Würzburg\", \"Würzburg Richtung Ulm\", \"Würzburg Richtung Fulda\", \"Fulda Richtung Würzburg\", \"Fulda Richtung Kassel\", \"Kassel Richtung Fulda\", \"Kassel Richtung Hannover\", \"Hannover Richtung Kassel\", \"Hannover Richtung Hamburg\", \"Hamburg Richtung Hannover\", \"Hamburg Richtung Flensburg\", \"Flensburg Richtung Hamburg\"]
for i in routes:
	label_name = i.lower().replace(\" \", \"_\").replace(\"ü\", \"ue\").replace(\"/\", \"_\")
	print(label_name + \".label \" + i.replace(\"Richtung\", \"→\"))
	print(label_name + \".info Anzahl der Verkehrswarnungen von \" + i)
	print(label_name + \".min 0\")

print(\"total.label Gesamt\")
print(\"total.info Anzahl der gesamten Verkehrswarnungen\")
print(\"total.min 0\")
"
}

output_values() {
	printf "plugins.value %d\n" $(number_of_plugins)
}

number_of_warnings() {
	curl -sX 'GET' "https://verkehr.autobahn.de/o/autobahn/$1/services/warning" -H 'accept: application/json' | \
	python3 -c "import sys, json, re
warnings = [];
json_entries = json.load(sys.stdin)
autobahn = \"$1\"
routes = []
if autobahn == \"A8\":
	routes = [\"Salzburg Richtung München\", \"München Richtung Salzburg\", \"München Richtung Stuttgart\", \"Stuttgart Richtung München\", \"Stuttgart Richtung Karlsruhe\", \"Karlsruhe Richtung Stuttgart\"]
elif autobahn == \"A7\":
	routes = [\"Füssen/Reutte Richtung Ulm\", \"Ulm Richtung Füssen/Reutte\", \"Ulm Richtung Würzburg\", \"Würzburg Richtung Ulm\", \"Würzburg Richtung Fulda\", \"Fulda Richtung Würzburg\", \"Fulda Richtung Kassel\", \"Kassel Richtung Fulda\", \"Kassel Richtung Hannover\", \"Hannover Richtung Kassel\", \"Hannover Richtung Hamburg\", \"Hamburg Richtung Hannover\", \"Hamburg Richtung Flensburg\", \"Flensburg Richtung Hamburg\"]
occ = []
tot = 0
for i in routes:
	occ.append(0)

for i in json_entries[\"warning\"]: 
	if i[\"subtitle\"] in routes:
		index = routes.index(i[\"subtitle\"])
		occ[index] += 1
	else:
		routes.append(i[\"subtitle\"])
		occ.append(1)
for i in routes:
	label_name = i.lower().replace(\" \", \"_\").replace(\"ü\", \"ue\").replace(\"/\", \"_\")
	count = occ[routes.index(i)]
	tot += count
	print(label_name + \".value \" + str(count))

print(\"total.value \" + str(tot))
"
}

output_result() {
	echo "multigraph autobahn_a7"
	number_of_warnings "A7"
	echo ""
	echo "multigraph autobahn_a8"
	number_of_warnings "A8"
}

output_usage() {
	printf >&2 "%s - munin plugin to graph an example value\n" ${0##*/}
	printf >&2 "Usage: %s [config]\n" ${0##*/}
}

case $# in
	0)
		output_result
		;;
	1)
		case $1 in
			config)
				output_config
				;;
			*)
				output_usage
				exit 1
				;;
		esac
		;;
	*)
		output_usage
		exit 1
		;;
esac
